version: '2'
services:
  consul:
    image: datamgtcloud/consul:latest
    hostname: consul
    dns: 127.0.0.1
    restart: always
    ports:
    - "8500:8500"
    volumes:
    - /data/consul:/data
    environment:
    - CONSUL_OPTIONS=-bootstrap

  nginx:
    image: datamgtcloud/consulNginx:latest
    hostname: consul
    dns: 127.0.0.1
    restart: always
    ports:
    - "80:80"
    links:
    - consul:consul

  hub:
    image: datacleansing/hub:latest
    hostname: hub
    dns: 127.0.0.1
    restart: always
    links:
    - consul:consul

  repo:
    image: datacleansing/repo:latest
    hostname: repo
    dns: 127.0.0.1
    restart: always
    links:
    - consul:consul

  fileuploader:
    image: datacleansing/fileuploader:latest
    hostname: fileuploader
    dns: 127.0.0.1
    restart: always
    links:
    - consul:consul

  engine:
    image: datacleansing/engine:latest
    hostname: engine
    dns: 127.0.0.1
    restart: always
    links:
    - consul:consul
